/// Flutter icons RtFont
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  RtFont
///      fonts:
///       - asset: fonts/RtFont.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
///


/// package 添加字体图片   将字体文件夹资源放到lib文件夹中, IconData 的fontPackage为paclage的名称
library rt_font_icons;

import 'package:flutter/widgets.dart';

class RtFont {
  RtFont._();

  static const _kFontFam = 'RtFont';

  static const IconData close = const RTFontData(0xe800, fontFamily: _kFontFam);
  static const IconData clear = const RTFontData(0xe801, fontFamily: _kFontFam);
  static const IconData location = const RTFontData(0xe802, fontFamily: _kFontFam);
  static const IconData weixuanyuanquan = const RTFontData(0xe803, fontFamily: _kFontFam);
  static const IconData check = const RTFontData(0xe804, fontFamily: _kFontFam);
  static const IconData warn = const RTFontData(0xe805, fontFamily: _kFontFam);
  static const IconData success_1_1 = const RTFontData(0xe806, fontFamily: _kFontFam);
  static const IconData arrowdown = const RTFontData(0xe807, fontFamily: _kFontFam);
  static const IconData arrowup = const RTFontData(0xe808, fontFamily: _kFontFam);
  static const IconData dagou = const RTFontData(0xe809, fontFamily: _kFontFam);
  static const IconData arrow_left = const RTFontData(0xe80a, fontFamily: _kFontFam);
  static const IconData nodata_message = const RTFontData(0xe80b, fontFamily: _kFontFam);
  static const IconData nodata_file = const RTFontData(0xe80c, fontFamily: _kFontFam);
  static const IconData nodata_topic = const RTFontData(0xe80d, fontFamily: _kFontFam);
  static const IconData nodata_search = const RTFontData(0xe80e, fontFamily: _kFontFam);
  static const IconData location1 = const RTFontData(0xe80f, fontFamily: _kFontFam);
  static const IconData dagou1 = const RTFontData(0xe810, fontFamily: _kFontFam);
  static const IconData fenxiang = const RTFontData(0xe811, fontFamily: _kFontFam);
  static const IconData fanhui = const RTFontData(0xe812, fontFamily: _kFontFam);
  static const IconData guanbi = const RTFontData(0xe813, fontFamily: _kFontFam);
  static const IconData bofang = const RTFontData(0xe814, fontFamily: _kFontFam);
  static const IconData kefu = const RTFontData(0xe815, fontFamily: _kFontFam);
  static const IconData shenfenzheng = const RTFontData(0xe816, fontFamily: _kFontFam);
  static const IconData quanping = const RTFontData(0xe817, fontFamily: _kFontFam);
  static const IconData duigou = const RTFontData(0xe818, fontFamily: _kFontFam);
  static const IconData shuoming = const RTFontData(0xe819, fontFamily: _kFontFam);
  static const IconData zanting = const RTFontData(0xe81a, fontFamily: _kFontFam);
  static const IconData shoucang = const RTFontData(0xe81b, fontFamily: _kFontFam);
  static const IconData saoyisao = const RTFontData(0xe81c, fontFamily: _kFontFam);
  static const IconData wode = const RTFontData(0xe81d, fontFamily: _kFontFam);
  static const IconData shouye = const RTFontData(0xe81e, fontFamily: _kFontFam);
  static const IconData fenlei = const RTFontData(0xe81f, fontFamily: _kFontFam);
  static const IconData xiaoxi = const RTFontData(0xe820, fontFamily: _kFontFam);
  static const IconData faxian = const RTFontData(0xe821, fontFamily: _kFontFam);
  static const IconData sousuo = const RTFontData(0xe822, fontFamily: _kFontFam);
  static const IconData liulan = const RTFontData(0xe823, fontFamily: _kFontFam);
  static const IconData zhiding = const RTFontData(0xe824, fontFamily: _kFontFam);
  static const IconData xuanzhong = const RTFontData(0xe825, fontFamily: _kFontFam);
  static const IconData tabguanbi = const RTFontData(0xe826, fontFamily: _kFontFam);
  static const IconData kexuanzuobiankuang = const RTFontData(0xe827, fontFamily: _kFontFam);
  static const IconData zuoweibeijing = const RTFontData(0xe828, fontFamily: _kFontFam);
  static const IconData bukexuanzuo = const RTFontData(0xe829, fontFamily: _kFontFam);
  static const IconData yigouxuan = const RTFontData(0xe82a, fontFamily: _kFontFam);
  static const IconData weigouxuan = const RTFontData(0xe82b, fontFamily: _kFontFam);
  static const IconData guanyanren = const RTFontData(0xe82c, fontFamily: _kFontFam);
  static const IconData dingyue = const RTFontData(0xe82d, fontFamily: _kFontFam);
  static const IconData dizhiguanli = const RTFontData(0xe82e, fontFamily: _kFontFam);
  static const IconData daifukuan = const RTFontData(0xe82f, fontFamily: _kFontFam);
  static const IconData daishouhuo = const RTFontData(0xe830, fontFamily: _kFontFam);
  static const IconData huiyuan = const RTFontData(0xe831, fontFamily: _kFontFam);
  static const IconData weishiyong = const RTFontData(0xe832, fontFamily: _kFontFam);
  static const IconData pingjia = const RTFontData(0xe833, fontFamily: _kFontFam);
  static const IconData qiandao = const RTFontData(0xe834, fontFamily: _kFontFam);
  static const IconData zhuanchu = const RTFontData(0xe835, fontFamily: _kFontFam);
  static const IconData zhuanru = const RTFontData(0xe836, fontFamily: _kFontFam);
  static const IconData yanchurili = const RTFontData(0xe837, fontFamily: _kFontFam);
  static const IconData changyonggoupiaorenbianji = const RTFontData(0xe838, fontFamily: _kFontFam);
  static const IconData changyonggoupiaorenshanchu = const RTFontData(0xe839, fontFamily: _kFontFam);
  static const IconData shouhuodizhiyebianji = const RTFontData(0xe83a, fontFamily: _kFontFam);
  static const IconData dingdan = const RTFontData(0xe83b, fontFamily: _kFontFam);
  static const IconData youhuiquan = const RTFontData(0xe83c, fontFamily: _kFontFam);
  static const IconData weigouxuan1 = const RTFontData(0xe83d, fontFamily: _kFontFam);
  static const IconData yigouxuan1 = const RTFontData(0xe83e, fontFamily: _kFontFam);
  static const IconData warn_1 = const RTFontData(0xe83f, fontFamily: _kFontFam);
  static const IconData guanbi1 = const RTFontData(0xe840, fontFamily: _kFontFam);
  static const IconData jiajianzujianjiahao = const RTFontData(0xe841, fontFamily: _kFontFam);
  static const IconData cainixihuan = const RTFontData(0xe842, fontFamily: _kFontFam);
  static const IconData huanyihuan = const RTFontData(0xe843, fontFamily: _kFontFam);
  static const IconData faxianjihuo = const RTFontData(0xe844, fontFamily: _kFontFam);
  static const IconData wodedamaijihuo = const RTFontData(0xe845, fontFamily: _kFontFam);
  static const IconData damailogo = const RTFontData(0xe846, fontFamily: _kFontFam);
  static const IconData fail_1 = const RTFontData(0xe847, fontFamily: _kFontFam);
  static const IconData search = const RTFontData(0xe848, fontFamily: _kFontFam);
  static const IconData shimingrenzheng = const RTFontData(0xe849, fontFamily: _kFontFam);
  static const IconData liebiaoyedizhi = const RTFontData(0xe84a, fontFamily: _kFontFam);
  static const IconData daohangdizhi = const RTFontData(0xe84b, fontFamily: _kFontFam);
  static const IconData jubao = const RTFontData(0xe84c, fontFamily: _kFontFam);
  static const IconData Location = const RTFontData(0xe84d, fontFamily: _kFontFam);
  static const IconData arrow = const RTFontData(0xe84e, fontFamily: _kFontFam);
  static const IconData dacha = const RTFontData(0xe84f, fontFamily: _kFontFam);
  static const IconData fail_1_1 = const RTFontData(0xe850, fontFamily: _kFontFam);
  static const IconData success_1 = const RTFontData(0xe851, fontFamily: _kFontFam);
}


class RTFontData extends IconData{
  final String fontFamily;
  const RTFontData(int codePoint,{this.fontFamily}) : super(codePoint,fontFamily:RtFont._kFontFam,fontPackage:"rt_font_icons");

}
